home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('construction/', views.construction, name='index'),
]

portfolio/urls.py
from django.urls import path

from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.indexView, name='index'),
    path('<str:subappname>/', views.redirectSubApp, name='redirectsubapp'),
    path('overview/<str:username>/', views.PortfolioView, name='overview'),
    path('profile/<str:username>/', views.ProfileView, name='profile'),
    path('history/<str:username>/', views.HistoryView.as_view(), name='history'),
    path('transactions/<str:username>/', views.TransactionsView, name='transactions'),
    path('ranking/help/', views.RankingHelp, name='rankinghelp'),
    path('_get_portfolio', views.getPortfolio, name='getPortfolio'),
    path('writereport/<str:username>/',views.WriteReportView, name='writereport'),
    path('overview/<str:username>/addfollow/',views.AddFollowing,name='addfollow'),
]

stocksim/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = 'stocksim'
urlpatterns = [
    path('', include('home.urls'),name='home'),
    path('stockdb/', include('stockdb.urls')),
    path('agora/', include('agora.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('simulator/', include('simulator.urls')),
]

portfolio/models.py
import datetime
import time
import pytz
ptz = pytz.timezone("UTC")

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from stockdb.models import Ticker, DayPrice
from stockdb.makedb import updateTicker, get_last_price, setTicker
from portfolio.scheduler import quetrigger
import json

class Player(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def portfolio_default():
        return {"_cash": 100000. }
    portfolio = models.JSONField('portfolio',default=portfolio_default)
    pub_date = models.DateTimeField('date published')
    favrt_ticker = models.ManyToManyField(Ticker, related_name = "subscriber", blank = True)
    following = models.ManyToManyField("self", related_name = "followers", symmetrical=False, blank = True )
    
    def __str__(self):
        return self.user.username

    # Generate AssetHistory objects and call its setHistory function
    # pfchange indicates the change of portoflio in quantities (ex pfchange={date(2021,01,01):{'_cash':100000.}})
    # When pfchange = {} it assumes there is no change in quantity portfolio from the latest existing history
    def makeHistory(self,pfchange={}):

        if(self.assethistory_set.exists()):
            lasthist=self.assethistory_set.order_by('-Date')[0]
            lastdate = lasthist.Date

            if(str(lastdate) in pfchange):
                lasthist.quant = pfchange[str(lastdate)].copy()
            
            #time consuming line
            lasthist.setHistory()
            
            lasthist.save()
            
            portfolio = lasthist.quant
            lastdate += datetime.timedelta(days=1)

        else:
            portfolio = Player.portfolio_default()
            lastdate = self.pub_date.date()

        historyli=[]
        today=timezone.now().date()
        while(lastdate<=today):

            if(str(lastdate) in pfchange):
                portfolio = pfchange[str(lastdate)]

            historyli.append(
                AssetHistory(
                    player = self,
                    Date = lastdate,
                    asset = None,
                    quant = portfolio.copy(),
                    amount = None,
                    code = 0)
            )

            historyli[-1].setHistory()
            lastdate += datetime.timedelta(days=1)

        AssetHistory.objects.bulk_create(historyli)

        return

    # Generate pfchange based on exisitng trns objects and pass it to makeHistory
    # This function is a manual function especially when you reset DB,
    # because in the normal workflow makeTransaction already takes care of history generating when a transaction is placed
    def catchupHistory(self):
        pfchange = {}

        if(self.assethistory_set.filter(code__gt=0,code__lt=3).exists()):        
            lasthist=self.assethistory_set.filter(code__gt=0,code__lt=3).order_by('-Date')[0]
            portfolio = lasthist.quant.copy()
            lastdate = lasthist.Date + datetime.timedelta(days=1)
            self.assethistory_set.filter(Date__gt = lastdate).delete()
        else:
            portfolio = Player.portfolio_default()
            lastdate = self.pub_date.date()
        
        for trns in self.transaction_set.filter(
            pub_date__gte = datetime.datetime(lastdate.year,lastdate.month,lastdate.day,tzinfo=self.pub_date.tzinfo),
            validation = "SUCCESS").order_by('pub_date'):

            if(trns.pub_date.date()!= lastdate):
                pfchange[str(lastdate)]=portfolio.copy()
                lastdate=trns.pub_date.date()
            trns.applyTransaction(portfolio)
        pfchange[str(lastdate)]=portfolio.copy()        
        self.portfolio=portfolio
        self.save()
        self.makeHistory(pfchange)

    # Generate transaction object and when it is valid update portfolio and AssetHistory
    # This function is based on Transaction.applyTransaction and Player.makeHistory
    # Return a transaction code (eg "TRANSACTION_SUCCESS" "TRANSACTION_FAIL_QuantityMustBeINT")
    def makeTransaction(self,ticker,quantity):
        
        # Buy if quantity>0 and Sell if quantity<0
        # Legit transaction criteria:
        #   1. Integer qunatity (no fractional shares)
        #   2. Ticker data exists (no yfinance error)
        #   3. Consolidated model object creation/modification (no database error)

        # 1. fractional shares
        if(type(quantity)!=int):
            return "TRANSACTION_FAIL_QuantityMustBeINT"

        try:
            price=get_last_price(ticker)
            # 2. yfinance error
            if(price is None):
                return "TRANSACTION_FAIL_NoPriceInfo"

            trns=Transaction(
                player=self,
                pub_date = timezone.now(),
                ticker = ticker,
                quantity = quantity,
                price = price
            )

            res=trns.applyTransaction(self.portfolio)
            trns.save()
            feedTransaction(trns)
            if(res=="TRANSACTION_SUCCESS"):
                self.save()
                if(not Ticker.objects.filter(ticker=ticker).exists()):
                    setTicker(ticker)
                quetrigger(100)
            return res

        except Ticker.DoesNotExist:
            return "TRANSACTION_FAIL_Ticker.DoesNotExist"

        return "TRANSACTION_FAIL_UncaughtError"
    
class Like(models.Model):
    content_type = models.ForeignKey(ContentType,on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type','object_id')
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Reply(models.Model):
    content_type = models.ForeignKey(ContentType,on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type','object_id')
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length = 280)
    pub_date = models.DateTimeField('date publihsed', default=datetime.datetime.now)
  #  deleted = models.BooleanField(default=False)

    like = GenericRelation('Like', related_query_name='reply')    

class Feed(models.Model):
    content_type = models.ForeignKey(ContentType,on_delete=models.CASCADE, blank = True, null = True)
    object_id = models.PositiveIntegerField(blank = True, null = True)
    content_object = GenericForeignKey('content_type','object_id')

    #type = models.CharField(max_length = 32, db_index = True, default = 'not specified')
    last_update = models.DateTimeField(auto_now = True)

    pub_date = models.DateTimeField('date published',db_index=True)
    like_count = models.IntegerField(default = 0)
    reply_count = models.IntegerField(default = 0)
    tag = models.CharField(max_length = 32, db_index = True)
    content = models.JSONField()

    def __str__(self):
        return "%s,  %s, id: %s" % (self.content_type.name, self.tag, self.pk)

    def update(self):
        self.like_count = self.content_object.like.count()
        self.reply_count = self.content_object.reply.count()
        self.save()



def feedTransaction(trns):
    content = {'object_id':trns.id, 'ticker': trns.ticker,  'quantity': trns.quantity, 'price':trns.price }

    feedtrns = Feed(
        content_object = trns,
        pub_date = trns.pub_date,
        tag = str(trns.player),
        like_count = trns.like.count(),
        reply_count = trns.reply.count(),
        content = json.dumps(content)
    )
    feedtrns.save()


class Transaction(models.Model):
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published',db_index=True)
    ticker = models.CharField(max_length=16)
    quantity = models.IntegerField(default=0)
    price = models.FloatField(default=0)
    validation = models.CharField(max_length=16,null=True)
    like = GenericRelation('Like',related_query_name='trns')
    reply = GenericRelation('Reply',related_query_name = 'trns')
    feed = GenericRelation('Feed', related_query_name = 'trns')

    def __str__(self):
        if(self.quantity>=0):
            return " %s  BUY , %s , %s shares , at %.2f USD , ( %s ) ( %s )" % ( self.player, self.ticker, self.price, self.quantity, self.validation,self.pub_date)
        else:
            return " %s  SELL , %s , %s shares , at $%.2f USD , ( %s ) ( %s )" % ( self.player, self.ticker, self.price, -self.quantity, self.validation,self.pub_date)
    
    def viewlistformat(self):
        if(self.ticker == '_swing'):
            return " Gain , SWING TRADE GAME , for $%.2f" % (self.price)
        if(self.quantity>=0):
            return " BUY , %s , %s shares , at $%.2f , total %.2fk" % ( self.ticker, self.quantity, self.price, self.price * self.quantity/1000)
        else:
            return " SELL , %s , %s shares , at $%.2f, total %.2fk" % ( self.ticker,  -self.quantity, self.price, -self.price * self.quantity/1000)

    # Based on trns object information update a portfolio dictionary object
    # This does not save Player or AssetHistory object by itself
    # Return a transaction code (eg "TRANSACTION_SUCCESS" "TRANSACTION_FAIL_NotEnoughCash")
    def applyTransaction(self,portfolio):

        # Buy if quantity>0 and Sell if quantity<0
        # Legit transaction criteria:
        #   1. Final cash balance >= 0 (no margin transaction)
        #   2. No float precision error (ex (1e+20+1)==1e+20)
        #   3. Final equity qunatity >= 0 (no short sell)

        quantity=self.quantity
        price=self.price
        ticker=self.ticker
        
        #special transactions
        if(ticker[0]=='_'):
            if(ticker=='_swing' and (price<=1000)):

portfolio/forms.py
# from agora.models import Report
from django import forms
from .models import Player, Transaction, Reply
from stockdb.models import Ticker
from django.forms import ModelForm
from django.utils import timezone

#import threading

class TransactionForm(forms.Form):
    ticker = forms.CharField(label='Ticker', max_length=16, required=True)
    quantity = forms.IntegerField(label="Quantity", required=True)

    def makeTransaction(self, player):
        ticker = self.cleaned_data['ticker']
        if(ticker[0]!='_'):
            ticker=ticker.upper()
        return player.makeTransaction(ticker,self.cleaned_data['quantity'])

class ReplyForm(forms.Form):
    content = forms.CharField(max_length=280,required=False, label=False, widget=forms.Textarea(attrs={
        "rows":5,
        "placeholder":"Add a reply here (# to tag a user or a word e.g. #admin)",
        "style":"align-content:left;width:calc(100% - 15px);resize: vertical;"
}))
    flag = forms.CharField(max_length=5,required=True, label=False, widget=forms.HiddenInput())
    parenttype = forms.CharField(max_length=20, required = True, widget = forms.HiddenInput())
    parentpk = forms.IntegerField(widget=forms.HiddenInput(),required=False)
    replypk = forms.IntegerField(widget=forms.HiddenInput(),required=False)

    def makeReply(self,parent,user):
        
        kwargs={'content_object':parent,
                'user':user,
                'content':self.cleaned_data['content'],
                'pub_date':timezone.now(),}

        return Reply(**kwargs)

    def delReply(self,user):
        reply = Reply.objects.get(pk=self.cleaned_data['replypk'])
        if(reply.user.pk==user.pk):
            reply.delete()

portfolio/templates/portfolio/historyview.html
{% extends "base_portfolio.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "home/css/login.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/mybase.css" %}">
{{ form.media }}
{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}

{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% translate "Please correct the error below." %}{% else %}{% translate "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

{% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.2.2/d3.min.js"></script> {% endcomment %}
<script src="{% static "home/d3.v4.js" %}"></script>
<script src="{% static "home/d3-scale-chromatic.v1.min.js" %}"></script>

<script src="{% static 'portfolio/d3chart.js' %}"></script>

<svg width="calc( 100vw - 80px )">
</svg>
<div id="test"></div>
<script>
    
    const svg=d3.select("svg")
    chrt=new d3chart(svg,{{history_list|length}});
    {% if mag_ratio %}
    chrt.rectWidth=chrt.rectWidth*{{mag_ratio}};
    {% endif %}
    let portfolio={};
    let date="";
    let asset=0.;
    {% if history_list %}
        {% for history in history_list %}

            chrt.addRectRow({
                portfolio_quant:{{history.quant|safe}},
                portfolio_money:{{history.amount|safe}},
                date:"{{history.Date|date}}",
                asset:{{history.asset|safe}},
            })

        {% endfor %}
    {% else %}

    {% endif %}

    draginit();

    var loop = setInterval(() =>{
        if(chrt.animationPlaying<5){

            chrt.svg.selectAll("rect")
            .data(chrt.pointlist)
            .on("mouseover", handleMouseOver)
            .on("mouseout", handleMouseOut)
            .call(dragOn);
            clearInterval(loop);

        }
    }, 30);

    window.addEventListener('resize', resizeChrt);

    // http://bl.ocks.org/d3indepth/b6d4845973089bc1012dec1674d3aff8
    // use curve monotone y
    // https://archive.nytimes.com/www.nytimes.com/interactive/2012/10/15/us/politics/swing-history.html

</script>
{% endblock %}

portfolio/templates/portfolio/rankinghelp.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "home/css/dashboard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/mybase.css" %}">
{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content %}

<script src="{% static "portfolio/rankingbadge.v0.js" %}"></script>
<div id="content-main" style="
    display:flex;
    flex-direction:column;
    align-items: center;
    margin: 30px 0;
    font-family: 'Azonix';
">

</div>

<script>

    const content_main = document.getElementById('content-main')

    for(let i = 0 ; i < 11 ; i++){
        const div = document.createElement('div');
        content_main.appendChild(div)
        div.style.setProperty('display','flex');
        div.style.setProperty('justify-content','space-evenly');
        div.style.setProperty('align-items','center');
        div.style.setProperty('text-align','center');
        div.style.setProperty('height','40px');
        div.style.setProperty('margin','13px 0');
        div.style.setProperty('width','50%');
        div.innerHTML=`<div style="width:80px;color: var(--link-fg);">LEVEL&nbsp;${(i==10) ? '+' : i }</div>
            <svg style="width:13px" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"></svg>`;
        if(i == 0){
            div.innerHTML+=`<div style='width: 50px;'>\<${100*(2**(1/3)).toFixed(2)}k</div>`;
        }
        else if(i == 10){
            div.innerHTML+=`<div style='width: 50px;'>\>1M</div>`;
        }
        else{
            div.innerHTML+=`<div style='width: 50px;'>${100*(2**(i/3)).toFixed(2)}k</div>`;
        }
    }

    document.querySelectorAll('svg').forEach( (d,i) => {
        
        const level = i+1;
        const asset = 100000*(2**(i/3))+1
        
        d.innerHTML=npolyGen(i+3,25,75,11);//13);
        d.style.width='65px';
    });

    document.getElementById('content-main').querySelectorAll('p.badgeRow').forEach( (d,i) => {
        d.innerText += ((1.25992105)**i).toFixed(2);
    });

    
    

</script>

{% endblock %}

portfolio/templates/portfolio/transactionsview.html
{% extends "base_portfolio.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "home/css/dashboard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/mybase.css" %}">
{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content-sub %}

<div id="content-main">
    <div class="module" id="make-actions-module">
        
        <h2>{% translate 'Make Transaction (positive quantity to buy, negative quantity to sell)' %}</h2>
        <div id="formdiv" style="margin:10px;">
        {% if anotheruser %}
            <input type="submit" class="submit-row" value="{% translate 'You are not authorized to place an order for ' %}{{anotheruser}}">
        {% else %}
            <form autocomplete="off" action="{{ app_path }}" method="post" id="trns-form">
                {% csrf_token %}
                <label for="id_ticker">Ticker:</label>
                <div class="autocomplete">
                {{ form.ticker }}
                </div>
                <label for="id_quantity">Quantity:</label>
                {{ form.quantity }}
                <input id="valbutton" type="button" class="submit-row" onclick="validateButtonOn();" value="VALIDATE">
                <input id="submitbutton" type="submit" class="submit-row" value="BUY/SELL" disabled>
            </form>
        {% endif %}
        </div>
    </div>    
    
    <div class="module" id="recent-actions-module">
        <h2>{% translate 'Recent Transactions' %}</h2>
        <h3>{% if anotheruser %}{{ anotheruser }}'s{% else %}My{%endif%} transactions</h3>
            
            {% if not transaction_list %}
            <p>{% translate 'None available' %}</p>
            {% else %}
            <ul class="actionlist">
            {% for entry in transaction_list %}
            <li class="{% if entry.validation == "SUCCESS" %}{% if entry.quantity > 0 %}buyaction{% else %}sellaction{% endif %}{% else %} failaction {%endif%}">
                <a href="/agora/ticker/{{entry.ticker}}">{{ entry.viewlistformat }}</a>
                <br>
                <span class="mini quiet">Transaction #{{ entry.pk }} -- {{ entry.pub_date }} -- {{ entry.validation }}</span>
            </li>
            {% endfor %}
            </ul>
            {% endif %}
    </div>
</div>
<script type='text/javascript'>
    let trnsstatus="{{trnsstatus|safe}}";
    if(trnsstatus!="NA" && trnsstatus!="TRANSACTION_SUCCESS"){
        alert(trnsstatus);
    }
</script>

<script type='text/javascript'>

    async function validateButtonOn(){
        
        const formdiv=document.getElementById("formdiv");
        let ulDOM=null;
        if(!formdiv.querySelector('ul')){
            ulDOM=document.createElement("ul");
            ulDOM.className="actionlist";
            formdiv.appendChild(ulDOM);
        }
        else{
            ulDOM = formdiv.querySelector('ul');
        }
        const quantity = formdiv.querySelector('input[name="quantity"]').value;
        const ticker = formdiv.querySelector('input[name="ticker"]').value;
        
        const response = await fetch('/stockdb/_get_last_price?ticker='+ticker);
        const response_json = await response.json(); // parses JSON response into native JavaScript objects
        console.log(response_json)
        if("ERROR" in response_json){
            ulDOM.innerHTML=`<li class='failaction'>${response_json.ERROR}</li>`;
            return;
        }
        if(!("price" in response_json)){
            ulDOM.innerHTML=`<li class='failaction'>UNCAUGHT ERROR</li>`;
            return;
        }

        const price = response_json.price;

        document.getElementById("valbutton").setAttribute("disabled","disabled");
        document.getElementById("submitbutton").removeAttribute("disabled");

        ulDOM.innerHTML=`
        <li class="${ quantity > 0 ? 'buyaction' : 'sellaction'}">
            <a href="/agora/ticker/${ticker}">
                ${ quantity > 0 ? 'BUY' : 'SELL'} , ${ticker} , ${Math.abs(quantity)} shares , at \$${price.toFixed(2)}, total ${(Math.abs(price*quantity)).toFixed(2)}
            </a>
        </li>`
    }
    function validateButtonOff(e){
        if(document.getElementById("valbutton").hasAttribute("disabled") && e.target.id!="submitbutton"){
            document.getElementById("valbutton").removeAttribute("disabled");
            document.getElementById("submitbutton").setAttribute("disabled","disabled");
        }
    }
    document.addEventListener('mousedown', validateButtonOff );

</script>

<script>
    
    /*make a ticker list importing static s&p 500 file*/
    let tickers = [];

    /*execute a function that upload and process s&p 500 text file*/
    async function getTicker(){
        const response = await fetch("{% static 'portfolio/snp500.txt' %}")
        const response_text = await response.text();
        return response_text.split('\n');
    }

    function processData(allText) {
        /* This is a function that convert a text file to a list file
        note that the "tickers" list must be referenced beforehand.

        - input: text file
        - output: "tickers" list file */

        let allTextLines = allText.split('\r\n');
        let lineIdx = 0;
        
        while (lineIdx < allTextLines.length){
            lineIdx += 1;
            let currentLine = allTextLines[lineIdx]
            tickers.push(currentLine);
        };

        return tickers;
    }    

    function autocomplete(user_input, tickers) {
    /* This is the autocomplete function takes two arguments: 
    1. user_input: user input parameters
    2. tickers : The list of stock tickers of possible autocompleted vaules */

    let currentFocus;

    /*execute a function when a user writes texts in the text field:*/
    user_input.addEventListener("input", function(e) {
        let div_1st, div_2nd, input_value = this.value;

        /*close any already open lists of autocompleted tickers*/
        closeAllLists();
        if (!input_value) {return false;}
        currentFocus = -1;

        /*create the first DIV element that will contain the items (values):
        and append the first DIV element as a child of the autocomplete container*/
        div_1st = document.createElement("DIV");
        div_1st.setAttribute("id", this.id + "autocomplete-list");
        div_1st.setAttribute("class", "autocomplete-items");
        this.parentNode.appendChild(div_1st);

        /*for each ticker in tickers */
        for (let i = 0; i < tickers.length -1; i++) {

            /*check if the ticker include the letters that user wrote in the text field*/
            if (tickers[i].toUpperCase().includes(input_value.toUpperCase())) {

            /*create the second DIV element for each matching element
            Then, slice the name of the ticker(bold) and information parts in the ticker */
            div_2nd = document.createElement("DIV");
            let ticker_end = tickers[i].indexOf(',')
            let company_end = tickers[i].lastIndexOf(',')
            div_2nd.innerHTML = "<strong>" + tickers[i].substr(0, ticker_end) + "</strong>";
            div_2nd.innerHTML += "   "+ tickers[i].substr(ticker_end + 1, );
            div_2nd.innerHTML += "<input type='hidden' value='" + tickers[i] + "'>";

            /*execute a function that print the ticker name on the textfield 
            when the user clicks on the ticker value (DIV element):*/
            div_2nd.addEventListener("click", function(e) {
                user_input.value = this.getElementsByTagName("input")[0].value.substr(0, ticker_end);
                closeAllLists();
            });

            div_1st.appendChild(div_2nd);
            }
        }
        });
    
    /*execute a function presses a key on the keyboard:*/
    user_input.addEventListener("keydown", function(e) {
    let x = document.getElementById(this.id + "autocomplete-list");
    if (x) x = x.getElementsByTagName("div");
    if (e.keyCode == 40) {
        /*If the arrow DOWN key is pressed,
        increase the currentFocus variable
        and make the current item more visible:*/
        currentFocus++;
        addActive(x);
    } else if (e.keyCode == 38) { 
        /*If the arrow UP key is pressed,
        decrease the currentFocus variable
        and make the current item more visible:*/
        currentFocus--;
        addActive(x);
    } else if (e.keyCode == 13) {
        /*If the ENTER key is pressed, 
        prevent the form from being submitted,
        and simulate a click on the "active" item*/
        e.preventDefault();
        if (currentFocus > -1) {
            if (x) x[currentFocus].click();
        }
    }
});

    function addActive(x) {
        /*This is the function that classifies a ticker as "active":*/

        /*return false if is not excuted*/
        if (!x) return false;

        /*remove "active" class on all tickers before start*/
        removeActive(x);
        if (currentFocus >= x.length) currentFocus = 0;
        if (currentFocus < 0) currentFocus = (x.length - 1);
        /*add class "autocomplete-active":*/
        x[currentFocus].classList.add("autocomplete-active");
    }

    function removeActive(x) {
        /*This is the function removes the "active" class from all autocomplete tickers*/
        for (let i = 0; i < x.length; i++) {
        x[i].classList.remove("autocomplete-active");
        }
    }

    function closeAllLists(element) {
        /*close all autocomplete tickers in the document,
        except the one passed:*/
        let x = document.getElementsByClassName("autocomplete-items");
        for (let i = 0; i < x.length; i++) {
            if (element != x[i] && element != user_input) {
                x[i].parentNode.removeChild(x[i]);
            }
        }
    }

    /*execute a function when the user clicks a ticker in the document:*/
    document.addEventListener("click", function (e) {
        closeAllLists(e.target);
    });

}

getTicker().then(tickers => autocomplete(document.getElementById("id_ticker"), tickers));

</script>

{% endblock %}

portfolio/templates/portfolio/writereport.html
{% extends "base_portfolio.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "home/css/dashboard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/login.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/mybase.css" %}">
{{ form.media }}
{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content-sub %}
{% if portfolio %}
    <h3>{{portfolio}}  </h3>
    <p> {{portfolio.amount}} </p>
{% endif %}
<form action="{{ app_path }}" method="post" id="memo-form" style="padding: 10px 0;">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="flag" id="id_flag" value="add"/>
    <input type="submit" class="submit-row" value="{% translate 'Submit' %}" style="float: right;">
</form>

{% endblock %}

portfolio/templates/portfolio/writereview.html
{% extends "base_portfolio.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "home/css/dashboard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/login.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/mybase.css" %}">
{{ form.media }}
{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content-sub %}
<form action="{{ app_path }}" method="post" id="memo-form" style="padding: 10px 0;">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="flag" id="id_flag" value="add"/>
    <input type="submit" class="submit-row" value="{% translate 'Submit' %}" style="float: right;">
</form>

{% endblock %}