agora/urls.py
from django.urls import path

from . import views

app_name = 'agora'
urlpatterns = [
    path('', views.index, name='index'),
    path('feeds/',views.FeedsView, name = "feed"),
    path('hashtag/<str:tag>', views.MemoTagsView, name='agoratag'),
    path('ticker/<str:ticker>/', views.TickerView, name='agoraticker'),
    path('ticker/<str:ticker>/addfav/', views.AddFavorite, name='addfav'),
    path('_addlike/', views.AddLike, name='addlike'),
    path('_addreply/', views.AddReply, name='addreply'),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name='index'),
    path('construction/', views.construction, name='index'),
]

stocksim/urls.py
from django.contrib import admin
from django.urls import include, path

app_name = 'stocksim'
urlpatterns = [
    path('', include('home.urls'),name='home'),
    path('stockdb/', include('stockdb.urls')),
    path('agora/', include('agora.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('simulator/', include('simulator.urls')),
]

agora/models.py
from django.db import models

from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from portfolio.models import Player, Like, Reply, Feed, pseudoAssetHistory
from stockdb.models import Ticker
import json
import re

# Create your models here.

#URL_REGEX = re.compile(r'''((\#(\w+)|https://|http://)[^ <>'"{},.|\\^`[\]]*)''')
URL_REGEX = re.compile(r'''((https://|http://)[^ <>'"{},.|\\^`[\]]*)''')
def encode_links(unencoded_string):
    # def tagGen(match):
    #     if match.group(0).startswith('#'):
    #         link="/agora/hashtag/"+match.group(0)[1:]
    #     else:
    #         link=match.group(0)
    #     return "<a href='"+link+"'>"+match.group(0)+"</a>"
    # return URL_REGEX.sub(tagGen, unencoded_string)
    encoded_str=URL_REGEX.sub(r"<a href='\1'>\1</a>", unencoded_string)
    tags=re.findall(r"#(\w+)", unencoded_string)
    for tag in tags:
        #if not (tag in {'https','http'}):
        encoded_str=encoded_str.replace("#"+tag,"<a href='/agora/hashtag/"+tag+"'>#"+tag+"</a>")
    return encoded_str

#encode_links("https://namver/#/esg #ddfrt,#efw zd #https://namve")

class Memo(models.Model):
    ticker = models.ForeignKey(Ticker, on_delete=models.CASCADE)
    player = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL)
    author = models.CharField(max_length=32)
    content = models.CharField(max_length=280)
    pub_date = models.DateTimeField('date published',db_index=True)
    isSubMemo = models.BooleanField(default=False,db_index=True)
    deleted = models.BooleanField(default=False)
    like = GenericRelation('portfolio.Like',related_query_name='memo')
    reply = GenericRelation('portfolio.Reply',related_query_name = 'memo')

    def __str__(self):
        return self.content
    
    @property
    def calIsSubMemo(self):
        self.isSubMemo=subMemo.objects.filter(pk=self.pk).exists()
        return self.isSubMemo

    @property
    def getInnerHTML(self):
        if(self.deleted):
            return "[ This message was deleted ]"
        return encode_links(self.content)

    def setMemoTags(self):
        existingTags=set(map(lambda x : x['tag'] , self.memotag_set.values('tag')))
        tags=re.findall(r"#(\w+)", self.getInnerHTML)
        tags.append(self.ticker.ticker)
        tags.append(self.author)
        tagObjs=[]
        for tag in set(tags):
            if not tag in existingTags:
                tagObjs.append(MemoTag(memo=self,tag=tag))
        MemoTag.objects.bulk_create(tagObjs)

class subMemo(Memo):
    parent = models.ForeignKey(Memo, on_delete=models.CASCADE, related_name="children")

class MemoTag(models.Model):
    memo = models.ForeignKey(Memo, on_delete=models.CASCADE)
    tag = models.CharField(max_length=32,db_index=True)

    def getMemos(tag):
        if(tag==None):
            memotags=MemoTag.objects.order_by('-memo__pub_date')[:14]
        else:
            memotags=MemoTag.objects.filter(tag=tag).order_by('-memo__pub_date')
        withoutRep=[]
        pkset=set()
        for memotag in memotags:
            if not memotag.memo.pk in pkset:
                pkset.add(memotag.memo.pk)
                withoutRep.append(memotag.memo)
        return withoutRep

STATUS = (
    (0, "DRAFT"), 
    (1,"Publish")
)

class Report(models.Model):
    title =  models.CharField(max_length= 200)
    player = models.ForeignKey(Player, null=True, on_delete=models.SET_NULL)
    author = models.CharField(max_length=32)
    pub_date = models.DateTimeField('date published', db_index = True)
    content = models.TextField()
    status = models.IntegerField(choices=STATUS, default = 0)
    deleted = models.BooleanField(default=False)
    like = GenericRelation('portfolio.Like',related_query_name='review')
    reply = GenericRelation('portfolio.Reply',related_query_name = 'review')
    feed = GenericRelation('portfolio.Feed', related_query_name = 'review')

    def __str__(self):
        return self.title

    class Meta:
        abstract = True

class PortfReview(Report):
    portfolio = models.ForeignKey(pseudoAssetHistory, on_delete=models.CASCADE)

class TickerReport(Report):
    ticker = models.ForeignKey(Ticker, on_delete=models.CASCADE)

    
def feedMemo(memo):
    content = {'object_id':memo.id, 'ticker': memo.ticker.ticker,  'content': memo.content }

    feedmemo = Feed(
        type =  'Memo', 
        pub_date = memo.pub_date,
        tag =  str(memo.author),
        like_count = memo.like.count(),
        reply_count = memo.reply.count(),
        content = json.dumps(content),
    )
    feedmemo.save()

def feedPortfreview(review):
    content_preview = review.content[:100] if len(review.content) > 100 else review.content
    content = {'type': 'Portfreview', 
    'title': review.title,
    'object_id':review.id,  
    'asset': review.portfolio.asset, 
    'quant': review.portfolio.quant, 
    'amount': review.portfolio.amount, 
    'Date':str(review.portfolio.Date),
    'content_preview': content_preview  }

    feedrvw = Feed(
        content_object = review,
        pub_date = review.pub_date,
        tag =  str(review.author),
        like_count = review.like.count(),
        reply_count = review.reply.count(),
        content = json.dumps(content)
    )
    feedrvw.save()

def feedTickerreport(report):
    content_preview = report.content[:100] if len(report.content) > 100 else report.content
    content = {'title': report.title, 'object_id': report.id, 'ticker': str(report.ticker), 'content_preview': content_preview }

    feedrvw = Feed(
        content_object = report,
        pub_date = report.pub_date,
        tag = str(report.player),
        like_count = report.like.count(),
        reply_count = report.reply.count(),
        content = json.dumps(content)
    )
    feedrvw.save()

agora/forms.py
from django import forms
from .models import Memo, MemoTag, TickerReport, subMemo, PortfReview
from stockdb.models import Ticker
from django.utils import timezone

from django.shortcuts import render
from django.http import HttpResponseRedirect

class MemoForm(forms.Form):
    content = forms.CharField(max_length=280,required=True, label=False, widget=forms.Textarea(attrs={
        "rows":5,
        "placeholder":"Add a memo here (# to tag a user or a word e.g. #admin)",
        "style":"align-content:left;width:calc(100% - 15px);resize: vertical;"
}))
    flag = forms.CharField(max_length=5,required=True, label=False, widget=forms.HiddenInput())
    parentpk = forms.IntegerField(widget=forms.HiddenInput(),required=False)
    
    def delMemo(self,ticker,user):
        memo = Memo.objects.get(pk=self.cleaned_data['parentpk'])
        if(memo.player.user.pk==user.pk):
            memo.deleted = True
            memo.save()
            form = MemoForm()
            return HttpResponseRedirect('/agora/ticker/'+ticker)
        else:
            form = MemoForm()
            return render(request,'agora/TickerView.html',{
                    'memo_list' : MemoForm.getMemoFormlist(tickerObj,request.user),
                    'form' : form,
                    'alert_msg': "ERROR: YOU ARE NOT AUTHORIZED TO DELETE IT" })
       

    def makeMemo(self,tickerObj,user):
        
        kwargs={'ticker':tickerObj,
                'player':user.player_set.all()[0],
                'author':user.username,
                'content':self.cleaned_data['content'],
                'pub_date':timezone.now(),}

        if self.cleaned_data['parentpk']:
            kwargs['parent']=Memo.objects.get(pk=self.cleaned_data['parentpk'])
            kwargs['isSubMemo']=True
            return subMemo(**kwargs)
        else:
            return Memo(**kwargs)
    
    def getMemoFormlist(tickerObj,user):
        mainMemos=Memo.objects.filter(ticker=tickerObj,isSubMemo=False).order_by("-pub_date")
        memolist=[]
        for memo in mainMemos:
            memolist.append({'memo':memo,'ischild':False, 'addform':False,'parentpk':memo.pk,'delenable':(user.pk==memo.player.user.pk)})
            for child in memo.children.order_by("pub_date"):
                memolist.append({'memo':child,'ischild':True, 'addform':False ,'parentpk':memo.pk,'delenable':(user.pk==child.player.user.pk)})
            memolist[-1]['addform']=MemoForm(initial={'parentpk':memo.pk})
            if(len(memolist)>100):
                break
        return memolist
             
class TickerReportForm(forms.ModelForm):
    class Meta:
        model = TickerReport
        fields = ['title','ticker','status','content']
        widgets = {
            'title': forms.Textarea(attrs={
            "rows":1,
            "placeholder":"Ticker Report",
            "style":"align-content:left;width:calc(100% - 15px);resize: vertical;"
        }),
            'content': forms.Textarea(attrs={
            "rows":15,
            "placeholder":"Add your analysis on the ticker here. (# to tag a user or a word e.g. #admin)",
            "style":"align-content:left;width:calc(100% - 15px);resize: vertical;"
        })
        }

    def makeReport(self,user):

        kwargs={
                'title': self.cleaned_data['title'],
                'player': user.player_set.all()[0],
                'author': user,
                'pub_date':timezone.now(),
                'content':self.cleaned_data['content'],
                'status': self.cleaned_data['status'],
                'ticker': self.cleaned_data['ticker']
                }
        return TickerReport(**kwargs)
        

class PortfReviewForm(forms.ModelForm):
    class Meta:
        model = PortfReview
        fields = ['title','status','content','portfolio']
        widgets = {
            'title': forms.Textarea(attrs={
            "rows":1,
            "placeholder":"Portfolio Review",
            "style":"align-content:left;width:calc(100% - 15px);resize: vertical;"
        }),
            'content': forms.Textarea(attrs={
            "rows":15,
            "placeholder":"Add your reasoning on your portfolio here. (# to tag a user or a word e.g. #admin)",
            "style":"align-content:left;width:calc(100% - 15px);resize: vertical;"
        }),
        }

    def makeReview(self,user):
        player = user.player_set.all()[0]
        kwargs={
                'title': self.cleaned_data['title'],
                'player': player,
                'author': user,
                'pub_date':timezone.now(),
                'content':self.cleaned_data['content'],
                'status': self.cleaned_data['status'],
                'portfolio': self.cleaned_data['portfolio']
                }
        return PortfReview(**kwargs)

agora/templates/agora/tickerview.html
{% extends "base_portfolio.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "home/css/dashboard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/mybase.css" %}">
{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content %}

<script src="{% static "home/d3.v4.js" %}"></script>
<script src="{% static "home/dbfetch.js" %}"></script>
<script src="{% static "portfolio/d3graph.v0.1.js" %}"></script>
<script src="{% static "home/functions.v0.200817.js" %}"></script>
<script src="http://kit.fontawesome.com/2d323a629b.js" crossorigin = "anonymous"></script>

<script>
    function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
    }
    const option = {
        method: "POST",
        credentials: "same-origin",
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json; charset=UTF-8',
            'X-CSRFToken': getCookie('csrftoken')
        },
    };

    async function addFavorite() {
        try {
            const response = await fetch("addfav/", option);
            const response_json = await response.json();
            const subscribing = document.getElementById("substatus");

            if(response_json.issubscribed){
                subscribing.innerHTML = "<i class='fas fa-star' style = 'font-size:21px; color:white'></i>";
            }
            else{
                subscribing.innerHTML = "<i class='far fa-star' style = 'font-size:21px; color: white'></i>";
            }
        } catch (err){
            console.error("Error");
        }
    };
</script>

<div id="content-main" style="margin-top:100px">


    <div class="module" id="chrt-container" style="padding:10px;">
        <div class="titleshow" style="display:flex;background:#264b5d">
            <h2 style="font-size: 21px;">{{tickerObj.ticker}} - {{tickerObj.name}}</h2>
            <button onclick="addFavorite();" style="background:none;border:none;margin:0;padding:0;cursor: pointer;" type="button">
            {% if subscribed  %}
            <div id="substatus"><i class="fas fa-star" style = "font-size:21px; color:white"></i></div>
            {% else %}
            <div id="substatus" ><i class="far fa-star" style = "font-size:21px; color: white"></i></div>
            {% endif %}
        </button>
        </div>

        <svg id='graph' style='width:100%'></svg>
        <script type="text/javascript">

        document.getElementById('content').style.setProperty('max-width','none');
        
        const window_size = 200 ;
        const strt_date_max1 = window.localdb_meta.__todayind - 10 * window_size;
        const strt_date_max2 = window.localdb_meta.__todayind - 1 * window_size;
        const graph=new d3graph(d3.select("svg#graph"),0)
        const graphDOM=document.getElementById("graph");
        const chrt_container=document.getElementById("chrt-container");
        window.gr=graph;
        graph.y2color=null;
        graph.margin = {top: 20, right: 20, bottom: 20, left: 40};

        let key='ticker__{{tickerObj.ticker}}';
        let fetchedDat = window.localdb[key];
        if(fetchedDat){
            initDraw(fetchedDat)
        }
        if( (!fetchedDat) || fetchedDat.strt_date>strt_date_max1 || fetchedDat.end_date<window.localdb_meta.__todayind){
            let req={};
            req[key]=strt_date_max1;
            fetchDB(req).then((response_json)=>{
                if(!(key in window.localdb)){
                    alert('No data available now');
                    window.location = '/agora/';
                }
                fetchedDat = window.localdb[key];
                initDraw(fetchedDat);
                saveLocalDB();
            })
        };
        graphDOM.addEventListener("wheel", function(e) {
            scrollZoom(e.deltaY);
            event.preventDefault();
        }, false);

        function initDraw(fetchedDat){
            graph.data=[]
            graph.strt_date = Math.max(strt_date_max1,fetchedDat.strt_date);
            graph.plot_index = Math.max(0,strt_date_max2 - graph.strt_date);
            
            transpose([
                fetchedDat.High.slice(graph.strt_date - fetchedDat.strt_date),
                fetchedDat.Low.slice(graph.strt_date - fetchedDat.strt_date),
                fetchedDat.Open.slice(graph.strt_date - fetchedDat.strt_date),
                fetchedDat.Close.slice(graph.strt_date - fetchedDat.strt_date)
            ]).forEach( d => {
                graph.appendDatum(d);
            })

            graph.width=graphDOM.clientWidth
            graph.height=Math.min(600,window.innerHeight*0.8,graph.width);
            graphDOM.style.height=graph.height+"px";
            //graph.draw();
            graph.update();
            window.addEventListener('resize', resize)
            document.addEventListener('fullscreenchange',resize)
        }

        function resize(){
            document.getElementById("graph").style.width=document.getElementById("chrt-container").clientWidth;
            graph.width=graphDOM.clientWidth
            graph.height=Math.min(600,window.innerHeight*0.8,graph.width);
            graphDOM.style.height=graph.height+"px";
            graph.update();
        }

        function scrollZoom(dy){
            graph.plot_index = Math.max( 0 , Math.min( graph.data.length-160 , graph.plot_index - Math.floor(dy/4) ) );
            resize();
        }
        </script>
    </div>

    <div class="module" id="recent-actions-module">
        <div style="margin:10px;">
            {% if user.is_authenticated %}
            <form action="{{ app_path }}" method="post" id="memo-form" style="padding: 10px 0;display:flex;">
                {% csrf_token %}
                {{ form }}
                <input type="hidden" name="flag" id="id_flag" value="add"/>
                <input type="submit" class="submit-row" value="{% translate 'Add' %}" style="float: right;">
            </form>
            {% else %}
            <input type="submit" class="submit-row" value="Log In is required to leave a memo">
            {% endif %}

        </div>

    <h2>{% translate 'Recent Memos' %}</h2>
        {% if not memo_list %}
        <div><p>{% translate 'No memo yet' %}</p></div>
        {% else %}
        <ul class="memolist">
        {% for entry in memo_list %}
        <li class="memo">
            {% if entry.ischild%}
            <div class="memo-indent"></div>
            {% endif %}
            <div class="memo-name"><a href="/portfolio/overview/{{ entry.memo.author }}">{{ entry.memo.author }}</a></div>
            <span class="memo-content"> {{ entry.memo.getInnerHTML | safe }}</span>
            <div class="memo-date">
                <span class="small quiet">{{ entry.memo.pub_date | date:"Y/m/d" }}</span>
                <div>
                {% if entry.addform %}
                <button type="button" onclick="document.getElementById('memo-form-{{entry.parentpk}}').style.display='flex';">reply</button>
                {% endif %}
                {% if entry.delenable %}
                <form action="{{ app_path }}" method="post" id="del-form-{{entry.memo.pk}}">
                    {% csrf_token %}
                    <input type="hidden" name="content" id="id_content" value="None" />
                    <input type="hidden" name="flag" value="del" />
                    <input type="hidden" name="parentpk" id="id_parentpk" value="{{ entry.memo.pk }}">
                    <button type="button" class='del' style="color:var(" onclick="document.getElementById('del-form-{{entry.memo.pk}}').submit();return false;">del</button>
                </form>
                {% endif %}
                </div>
            </div>
            {% if entry.addform %}
            </li><li class="memo">
            <div class="memo-indent"></div>
            <div class="memo-content">
            <form action="{{ app_path }}" method="post" id="memo-form-{{entry.parentpk}}" style="padding: 10px 0 35px 0;display:none;">
                {% csrf_token %}
                {{ entry.addform.content.errors }}
                {{ entry.addform.content }}
                <input type="hidden" name="flag" id="id_flag" value="add" />
                <input type="hidden" name="parentpk" id="id_parentpk" value="{{ entry.parentpk }}">
                <input type="submit" class="submit-row" value="{% translate 'Add' %}" style="float: right;">
            </form>
            </div>
            </li><li class="memo">
            {% endif %}
        </li>
        <hr>
        {% endfor %}
        </ul>
        {% endif %}

    </div>
</div>

{% endblock %}

{% block sidebar %}


{% if alert_msg %}
<script>
    alert("{{alert_msg}}");
    window.location.replace("/agora/")
</script>
{% endif %}
{% comment %}
<div id="content-related">
  {% include "admin/app_list.html" with app_list=app_list show_changelinks=True %}
</div>
{% endcomment %}
{% endblock %}

agora/templates/agora/tickerview_plotly.html
{% extends "base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "home/css/dashboard.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "home/css/mybase.css" %}">
{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block nav-sidebar %}{% endblock %}

{% block content %}
<div id="content-main">


    <div class="module" id="chrt-container" style="min-height:300px;">
    <h2 style="font-size: 21px;">{{tickerObj.ticker}} - {{tickerObj.name}}</h2>
        <div id="chartplot"></div>
        {% comment %} <script src="{% static "home/d3.v4.js" %}"></script>
        <script src="{% static "home/dbfetch.v0.js" %}"></script>
        <script src="{% static "portfolio/d3graph.v0.1.js" %}"></script>
        <script src="{% static "home/functions.v0.200817.js" %}"></script> {% endcomment %}
        <script src="{% static "home/dbfetch.v0.js" %}"></script>
        <script src="https://cdn.plot.ly/plotly-2.1.0.min.js"></script>
        <script id="asyncsrc" async src="{% static "home/plotly.js" %}"></script>
        <script type="text/javascript">
        function resize(){
            window.plotly.layout.width = document.getElementById("chrt-container").clientWidth;
            window.plotly.layout.height = Math.min(500,window.innerHeight*0.8,window.plotly.layout.width);
            window.plotly.plot();
        }

        window.addEventListener('resize', resize)
        document.addEventListener('fullscreenchange',resize)

        document.getElementById('asyncsrc').addEventListener('load', ()=>{
            window.plotly.layout.xaxis.autorange=false;
            delete window.plotly.layout.xaxis['rangeselector'];

            let key='ticker__{{tickerObj.ticker}}';
            if(key in window.localdb){
                window.plotly.enter(key);
                let dateli=window.plotly.data[window.plotly.dataInd[key]].x;
                let range=[Math.max(0,dateli.length-300),dateli.length-1];
                window.plotly.layout.xaxis.range = [dateli[range[0]], dateli[range[1]]];
                let yvalues=window.plotly.data[window.plotly.dataInd[key]].close.slice(range[0],range[1]+1);
                let yrange=[yvalues[0], yvalues[0]];
                yvalues.forEach(y => {
                    if(y){
                        if(y<yrange[0]){ yrange[0]=y; }
                        if(y>yrange[1]){ yrange[1]=y; }
                    }
                })
                if(typeof(yrange[0])=="number" && typeof(yrange[1])=="number"){
                    window.plotly.layout.yaxis2.autorange=false;
                    window.plotly.layout.yaxis2.range = [Math.log10(yrange[0]),Math.log10(yrange[1])];
                };
                resize();
                if(window.localdb_meta.__todayind-1500<window.localdb[key].strt_date){
                    let req={};
                    req[key]=window.localdb_meta.__todayind-1500;
                    fetchDB(req).then((response_json)=>{
                        window.plotly.enter(key);
                        resize();
                        saveLocalDB();
                    });
                }
            }
            else{
                let req={};
                req[key]=window.localdb_meta.__todayind-1500;
                fetchDB(req).then((response_json)=>{
                    window.plotly.enter(key);
                    let dateli=window.plotly.data[window.plotly.dataInd[key]].x;
                    let range=[Math.max(0,dateli.length-300),dateli.length-1];
                    window.plotly.layout.xaxis.range = [dateli[range[0]], dateli[range[1]]];
                    let yvalues=window.plotly.data[window.plotly.dataInd[key]].close.slice(range[0],range[1]+1);
                    let yrange=[yvalues[0], yvalues[0]];
                    yvalues.forEach(y => {
                        if(y){
                            if(y<yrange[0]){ yrange[0]=y; }
                            if(y>yrange[1]){ yrange[1]=y; }
                        }
                    })
                    if(typeof(yrange[0])=="number" && typeof(yrange[1])=="number"){
                        window.plotly.layout.yaxis2.autorange=false;
                        window.plotly.layout.yaxis2.range = [Math.log10(yrange[0]),Math.log10(yrange[1])];
                    };
                    resize();
                    saveLocalDB();
                });
            }
        })
        </script>
    </div>

    <div class="module" id="recent-actions-module">
        <div style="margin:10px;">
            {% if user.is_authenticated %}
            <form action="{{ app_path }}" method="post" id="memo-form" style="padding: 10px 0;display:flex;">
                {% csrf_token %}
                {{ form }}
                <input type="hidden" name="flag" id="id_flag" value="add"/>
                <input type="submit" class="submit-row" value="{% translate 'Add' %}" style="float: right;">
            </form>
            {% else %}
            <input type="submit" class="submit-row" value="Log In is required to leave a memo">
            {% endif %}

        </div>

    <h2>{% translate 'Recent Memos' %}</h2>
        {% if not memo_list %}
        <div><p>{% translate 'No memo yet' %}</p></div>
        {% else %}
        <ul class="memolist">
        {% for entry in memo_list %}
        <li class="memo">
            {% if entry.ischild%}
            <div class="memo-indent"></div>
            {% endif %}
            <div class="memo-name"><a href="/portfolio/overview/{{ entry.memo.author }}">{{ entry.memo.author }}</a></div>
            <span class="memo-content"> {{ entry.memo.getInnerHTML | safe }}</span>
            <div class="memo-date">
                <span class="small quiet">{{ entry.memo.pub_date | date:"Y/m/d" }}</span>
                <div>
                {% if entry.addform %}
                <button type="button" onclick="document.getElementById('memo-form-{{entry.parentpk}}').style.display='flex';">reply</button>
                {% endif %}
                {% if entry.delenable %}
                <form action="{{ app_path }}" method="post" id="del-form-{{entry.memo.pk}}">
                    {% csrf_token %}
                    <input type="hidden" name="content" id="id_content" value="None" />
                    <input type="hidden" name="flag" value="del" />
                    <input type="hidden" name="parentpk" id="id_parentpk" value="{{ entry.memo.pk }}">
                    <button type="button" class='del' style="color:var(" onclick="document.getElementById('del-form-{{entry.memo.pk}}').submit();return false;">del</button>
                </form>
                {% endif %}
                </div>
            </div>
            {% if entry.addform %}
            </li><li class="memo">
            <div class="memo-indent"></div>
            <div class="memo-content">
            <form action="{{ app_path }}" method="post" id="memo-form-{{entry.parentpk}}" style="padding: 10px 0 35px 0;display:none;">
                {% csrf_token %}
                {{ entry.addform.content.errors }}
                {{ entry.addform.content }}
                <input type="hidden" name="flag" id="id_flag" value="add" />
                <input type="hidden" name="parentpk" id="id_parentpk" value="{{ entry.parentpk }}">
                <input type="submit" class="submit-row" value="{% translate 'Add' %}" style="float: right;">
            </form>
            </div>
            </li><li class="memo">
            {% endif %}
        </li>
        <hr>
        {% endfor %}
        </ul>
        {% endif %}

    </div>
</div>

{% endblock %}

{% block sidebar %}


{% if alert_msg %}
<script>
    alert("{{alert_msg}}");
    window.location.replace("/agora/")
</script>
{% endif %}
{% comment %}
<div id="content-related">
  {% include "admin/app_list.html" with app_list=app_list show_changelinks=True %}
</div>
{% endcomment %}
{% endblock %}